export default [
  { name: 'slovenija', translation: 'SLOVENIJA' },
  { name: 'ajdovščina', translation: 'Ajdovščina' },
  { name: 'ankaran', translation: 'Ankaran' },
  { name: 'apače', translation: 'Apače' },
  { name: 'beltinci', translation: 'Beltinci' },
  { name: 'benedikt', translation: 'Benedikt' },
  { name: 'bistrica_ob_sotli', translation: 'Bistrica ob Sotli' },
  { name: 'bled', translation: 'Bled' },
  { name: 'bloke', translation: 'Bloke' },
  { name: 'bohinj', translation: 'Bohinj' },
  { name: 'borovnica', translation: 'Borovnica' },
  { name: 'bovec', translation: 'Bovec' },
  { name: 'braslovče', translation: 'Braslovče' },
  { name: 'brda', translation: 'Brda' },
  { name: 'brezovica', translation: 'Brezovica' },
  { name: 'brežice', translation: 'Brežice' },
  { name: 'cankova', translation: 'Cankova' },
  { name: 'celje', translation: 'Celje' },
  { name: 'cerklje_na_gorenjskem', translation: 'Cerklje na Gorenjskem' },
  { name: 'cerknica', translation: 'Cerknica' },
  { name: 'cerkno', translation: 'Cerkno' },
  { name: 'cerkvenjak', translation: 'Cerkvenjak' },
  { name: 'cirkulane', translation: 'Cirkulane' },
  { name: 'črenšovci', translation: 'Črenšovci' },
  { name: 'črna_na_koroškem', translation: 'Črna na Koroškem' },
  { name: 'črnomelj', translation: 'Črnomelj' },
  { name: 'destrnik', translation: 'Destrnik' },
  { name: 'divača', translation: 'Divača' },
  { name: 'dobje', translation: 'Dobje' },
  { name: 'dobrepolje', translation: 'Dobrepolje' },
  { name: 'dobrna', translation: 'Dobrna' },
  { name: 'dobrova-polhov_gradec', translation: 'Dobrova - Polhov Gradec' },
  { name: 'dobrovnik', translation: 'Dobrovnik' },
  { name: 'dol_pri_ljubljani', translation: 'Dol pri Ljubljani' },
  { name: 'dolenjske_toplice', translation: 'Dolenjske Toplice' },
  { name: 'domžale', translation: 'Domžale' },
  { name: 'dornava', translation: 'Dornava' },
  { name: 'dravograd', translation: 'Dravograd' },
  { name: 'duplek', translation: 'Duplek' },
  { name: 'gorenja_vas-poljane', translation: 'Gorenja vas - Poljane' },
  { name: 'gorišnica', translation: 'Gorišnica' },
  { name: 'gorje', translation: 'Gorje' },
  { name: 'gornja_radgona', translation: 'Gornja Radgona' },
  { name: 'gornji_grad', translation: 'Gornji Grad' },
  { name: 'gornji_petrovci', translation: 'Gornji Petrovci' },
  { name: 'grad', translation: 'Grad' },
  { name: 'grosuplje', translation: 'Grosuplje' },
  { name: 'hajdina', translation: 'Hajdina' },
  { name: 'hoče-slivnica', translation: 'Hoče - Slivnica' },
  { name: 'hodoš', translation: 'Hodoš/Hodos' },
  { name: 'horjul', translation: 'Horjul' },
  { name: 'hrastnik', translation: 'Hrastnik' },
  { name: 'hrpelje-kozina', translation: 'Hrpelje - Kozina' },
  { name: 'idrija', translation: 'Idrija' },
  { name: 'ig', translation: 'Ig' },
  { name: 'ilirska_bistrica', translation: 'Ilirska Bistrica' },
  { name: 'ivančna_gorica', translation: 'Ivančna Gorica' },
  { name: 'izola', translation: 'Izola' },
  { name: 'jesenice', translation: 'Jesenice' },
  { name: 'jezersko', translation: 'Jezersko' },
  { name: 'juršinci', translation: 'Juršinci' },
  { name: 'kamnik', translation: 'Kamnik' },
  { name: 'kanal', translation: 'Kanal ob Soči' },
  { name: 'kidričevo', translation: 'Kidričevo' },
  { name: 'kobarid', translation: 'Kobarid' },
  { name: 'kobilje', translation: 'Kobilje' },
  { name: 'kočevje', translation: 'Kočevje' },
  { name: 'komen', translation: 'Komen' },
  { name: 'komenda', translation: 'Komenda' },
  { name: 'koper', translation: 'Koper' },
  { name: 'kostanjevica_na_krki', translation: 'Kostanjevica na Krki' },
  { name: 'kostel', translation: 'Kostel' },
  { name: 'kozje', translation: 'Kozje' },
  { name: 'kranj', translation: 'Kranj' },
  { name: 'kranjska_gora', translation: 'Kranjska Gora' },
  { name: 'križevci', translation: 'Križevci' },
  { name: 'krško', translation: 'Krško' },
  { name: 'kungota', translation: 'Kungota' },
  { name: 'kuzma', translation: 'Kuzma' },
  { name: 'laško', translation: 'Laško' },
  { name: 'lenart', translation: 'Lenart' },
  { name: 'lendava', translation: 'Lendava' },
  { name: 'litija', translation: 'Litija' },
  { name: 'ljubljana', translation: 'Ljubljana' },
  { name: 'ljubno', translation: 'Ljubno' },
  { name: 'ljutomer', translation: 'Ljutomer' },
  { name: 'log-dragomer', translation: 'Log - Dragomer' },
  { name: 'logatec', translation: 'Logatec' },
  { name: 'loška_dolina', translation: 'Loška dolina' },
  { name: 'loški_potok', translation: 'Loški Potok' },
  { name: 'lovrenc_na_pohorju', translation: 'Lovrenc na Pohorju' },
  { name: 'luče', translation: 'Luče' },
  { name: 'lukovica', translation: 'Lukovica' },
  { name: 'majšperk', translation: 'Majšperk' },
  { name: 'makole', translation: 'Makole' },
  { name: 'maribor', translation: 'Maribor' },
  { name: 'markovci', translation: 'Markovci' },
  { name: 'medvode', translation: 'Medvode' },
  { name: 'mengeš', translation: 'Mengeš' },
  { name: 'metlika', translation: 'Metlika' },
  { name: 'mežica', translation: 'Mežica' },
  {
    name: 'miklavž_na_dravskem_polju',
    translation: 'Miklavž na Dravskem polju',
  },
  { name: 'miren-kostanjevica', translation: 'Miren - Kostanjevica' },
  { name: 'mirna', translation: 'Mirna' },
  { name: 'mirna_peč', translation: 'Mirna Peč' },
  { name: 'mislinja', translation: 'Mislinja' },
  { name: 'mokronog-trebelno', translation: 'Mokronog - Trebelno' },
  { name: 'moravče', translation: 'Moravče' },
  { name: 'moravske_toplice', translation: 'Moravske Toplice' },
  { name: 'mozirje', translation: 'Mozirje' },
  { name: 'murska_sobota', translation: 'Murska Sobota' },
  { name: 'muta', translation: 'Muta' },
  { name: 'naklo', translation: 'Naklo' },
  { name: 'nazarje', translation: 'Nazarje' },
  { name: 'nova_gorica', translation: 'Nova Gorica' },
  { name: 'novo_mesto', translation: 'Novo mesto' },
  { name: 'odranci', translation: 'Odranci' },
  { name: 'oplotnica', translation: 'Oplotnica' },
  { name: 'ormož', translation: 'Ormož' },
  { name: 'osilnica', translation: 'Osilnica' },
  { name: 'pesnica', translation: 'Pesnica' },
  { name: 'piran', translation: 'Piran' },
  { name: 'pivka', translation: 'Pivka' },
  { name: 'podčetrtek', translation: 'Podčetrtek' },
  { name: 'podlehnik', translation: 'Podlehnik' },
  { name: 'podvelka', translation: 'Podvelka' },
  { name: 'poljčane', translation: 'Poljčane' },
  { name: 'polzela', translation: 'Polzela' },
  { name: 'postojna', translation: 'Postojna' },
  { name: 'prebold', translation: 'Prebold' },
  { name: 'preddvor', translation: 'Preddvor' },
  { name: 'prevalje', translation: 'Prevalje' },
  { name: 'ptuj', translation: 'Ptuj' },
  { name: 'puconci', translation: 'Puconci' },
  { name: 'rače-fram', translation: 'Rače - Fram' },
  { name: 'radeče', translation: 'Radeče' },
  { name: 'radenci', translation: 'Radenci' },
  { name: 'radlje_ob_dravi', translation: 'Radlje ob Dravi' },
  { name: 'radovljica', translation: 'Radovljica' },
  { name: 'ravne_na_koroškem', translation: 'Ravne na Koroškem' },
  { name: 'razkrižje', translation: 'Razkrižje' },
  { name: 'rečica_ob_savinji', translation: 'Rečica ob Savinji' },
  { name: 'renče-vogrsko', translation: 'Renče - Vogrsko' },
  { name: 'ribnica', translation: 'Ribnica' },
  { name: 'ribnica_na_pohorju', translation: 'Ribnica na Pohorju' },
  { name: 'rogaška_slatina', translation: 'Rogaška Slatina' },
  { name: 'rogašovci', translation: 'Rogašovci' },
  { name: 'rogatec', translation: 'Rogatec' },
  { name: 'ruše', translation: 'Ruše' },
  { name: 'selnica_ob_dravi', translation: 'Selnica ob Dravi' },
  { name: 'semič', translation: 'Semič' },
  { name: 'sevnica', translation: 'Sevnica' },
  { name: 'sežana', translation: 'Sežana' },
  { name: 'slovenj_gradec', translation: 'Slovenj Gradec' },
  { name: 'slovenska_bistrica', translation: 'Slovenska Bistrica' },
  { name: 'slovenske_konjice', translation: 'Slovenske Konjice' },
  { name: 'sodražica', translation: 'Sodražica' },
  { name: 'solčava', translation: 'Solčava' },
  { name: 'središče_ob_dravi', translation: 'Središče ob Dravi' },
  { name: 'starše', translation: 'Starše' },
  { name: 'straža', translation: 'Straža' },
  { name: 'sveta_ana', translation: 'Sveta Ana' },
  {
    name: 'sveta_trojica_v_slov._goricah',
    translation: 'Sveta Trojica v Slov. goricah',
  },
  {
    name: 'sveti_andraž_v_slov._goricah',
    translation: 'Sveti Andraž v Slov. goricah',
  },
  { name: 'sveti_jurij_ob_ščavnici', translation: 'Sveti Jurij ob Ščavnici' },
  {
    name: 'sveti_jurij_v_slov._goricah',
    translation: 'Sveti Jurij v Slov. goricah',
  },
  { name: 'sveti_tomaž', translation: 'Sveti Tomaž' },
  { name: 'šalovci', translation: 'Šalovci' },
  { name: 'šempeter-vrtojba', translation: 'Šempeter - Vrtojba' },
  { name: 'šenčur', translation: 'Šenčur' },
  { name: 'šentilj', translation: 'Šentilj' },
  { name: 'šentjernej', translation: 'Šentjernej' },
  { name: 'šentjur', translation: 'Šentjur' },
  { name: 'šentrupert', translation: 'Šentrupert' },
  { name: 'škocjan', translation: 'Škocjan' },
  { name: 'škofja_loka', translation: 'Škofja Loka' },
  { name: 'škofljica', translation: 'Škofljica' },
  { name: 'šmarje_pri_jelšah', translation: 'Šmarje pri Jelšah' },
  { name: 'šmarješke_toplice', translation: 'Šmarješke Toplice' },
  { name: 'šmartno_ob_paki', translation: 'Šmartno ob Paki' },
  { name: 'šmartno_pri_litiji', translation: 'Šmartno pri Litiji' },
  { name: 'šoštanj', translation: 'Šoštanj' },
  { name: 'štore', translation: 'Štore' },
  { name: 'tabor', translation: 'Tabor' },
  { name: 'tišina', translation: 'Tišina' },
  { name: 'tolmin', translation: 'Tolmin' },
  { name: 'trbovlje', translation: 'Trbovlje' },
  { name: 'trebnje', translation: 'Trebnje' },
  { name: 'trnovska_vas', translation: 'Trnovska vas' },
  { name: 'trzin', translation: 'Trzin' },
  { name: 'tržič', translation: 'Tržič' },
  { name: 'turnišče', translation: 'Turnišče' },
  { name: 'velenje', translation: 'Velenje' },
  { name: 'velika_polana', translation: 'Velika Polana' },
  { name: 'velike_lašče', translation: 'Velike Lašče' },
  { name: 'veržej', translation: 'Veržej' },
  { name: 'videm', translation: 'Videm' },
  { name: 'vipava', translation: 'Vipava' },
  { name: 'vitanje', translation: 'Vitanje' },
  { name: 'vodice', translation: 'Vodice' },
  { name: 'vojnik', translation: 'Vojnik' },
  { name: 'vransko', translation: 'Vransko' },
  { name: 'vrhnika', translation: 'Vrhnika' },
  { name: 'vuzenica', translation: 'Vuzenica' },
  { name: 'zagorje_ob_savi', translation: 'Zagorje ob Savi' },
  { name: 'zavrč', translation: 'Zavrč' },
  { name: 'zreče', translation: 'Zreče' },
  { name: 'žalec', translation: 'Žalec' },
  { name: 'železniki', translation: 'Železniki' },
  { name: 'žetale', translation: 'Žetale' },
  { name: 'žiri', translation: 'Žiri' },
  { name: 'žirovnica', translation: 'Žirovnica' },
  { name: 'žužemberk', translation: 'Žužemberk' },
];
